receivers:
    otlp:
        protocols:
            grpc:

exporters:
    logging:

    zipkin:
        endpoint: "http://zipkin-collector:9411/api/v2/spans"
        format: proto

    otlp:
        endpoint: jaeger-all-in-one:4317
        tls:
            insecure: true

processors:
    batch:

extensions:
    health_check:
    pprof:
        endpoint: :1888

service:
    extensions: [pprof, health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging, zipkin, otlp]
